version: "3.8"
services:
  database:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plan_together
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: no
    networks:
      - app-network
  backend:
    container_name: backend
    build: ./PlanTogether-Backend
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/plan_together
      - END_TO_END_TEST_IP=http://frontend:3000
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    container_name: frontend
    build: ./PlanTogether-Frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge